# 管理员登录session键名
SESSION_LOGIN = "SESSION_LOGIN"

# 账号
SESSION_USER_ID = 'SESSION_USER_ID'

# 用户昵称
SESSION_USER_NAME = 'SESSION_USER_NAME'

# 用户类型
SESSION_USER_TYPE = "SESSION_USER_TYPE"


# 用户头像地址
SESSION_HEAD_PORTRAIT = "SESSION_HEAD_PORTRAIT"

"""
安全相关
"""

# 登录次数(失败一次后需要输入验证码)
SESSION_LOGIN_TIME = "SESSION_LOGIN_TIME"

# 验证码
SESSION_LOGIN_VALIDATE = "SESSION_LOGIN_VALIDATE"

# 登录重定向uri
SESSION_REDIRECT_URI = "SESSION_REDIRECT_URI"


